services:
  - type: web
    name: restaurants-backend
    env: node
    buildCommand: yarn install --frozen-lockfile && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 9696
    plan: free