apiVersion: v1
kind: Service
metadata:
  name: restaurants-service
  namespace: restaurants
  labels:
    app: restaurants-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 4242
    protocol: TCP
    name: http
  selector:
    app: restaurants-backend
